### ISSUE TITLE
Місце відпочинку 

### ISSUE THREAD

**Issue by irynaa-semchuk** [zoriana-melnyk/Trip-to-the-Carpathians#1]
Пропоную тур  Неймовірна Боржава: Великий Верх — водоспад Шипіт))

**Comment by zoriana-melnyk** [comment]
Цікаво, а які є ще варіанти?

**Comment by irynaa-semchuk** [comment]
Можна ще такий тур - Дикі Карпати: На Кукульські полонини:)

**Comment by zoriana-melnyk** [comment]
А якщо до того, щоб організувати подорож самостійно? Та піднятися на Говерлу?

**Comment by irynaa-semchuk** [comment]
Я згідна, давай організуємо самостійно тур, але я не хочу на Говерлу:(

**Comment by zoriana-melnyk** [comment]
Добре, обійдемось без Говерли. Що ти пропонуєш?

**Comment by irynaa-semchuk** [comment]
Можна поїхати в Яремче або у Славськ?))

**Comment by zoriana-melnyk** [comment]
Добре, тоді давай в Яремче!) До речі, недалеко від Яремче є дуже гарний Манявський водоспад)

**Comment by irynaa-semchuk** [comment]
Ок)Тоді  їдемо в Яремче)))

**Comment by irynaa-semchuk** [comment]
Кинь координати)

**Comment by zoriana-melnyk** [comment]
[https://www.google.com/maps/place/%D0%AF%D1%80%D0%B5%D0%BC%D1%87%D0%B5,+%D0%86%D0%B2%D0%B0%D0%BD%D0%BE-%D0%A4%D1%80%D0%B0%D0%BD%D0%BA%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B0+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C/@48.4560948,24.5062047,12z/data=!3m1!4b1!4m5!3m4!1s0x4737243a84944efd:0x1c5465f02903eff2!8m2!3d48.481557!4d24.5819174](url)

**Comment by zoriana-melnyk** [comment]
А ось розташування Манявського водоспаду:
[https://www.google.com/maps/place/%D0%9C%D0%B0%D0%BD%D1%8F%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9+%D0%B2%D0%BE%D0%B4%D0%BE%D1%81%D0%BF%D0%B0%D0%B4/@48.6256977,24.3035185,15z/data=!4m2!3m1!1s0x0:0xc7bcfba3a6820845?sa=X&ved=2ahUKEwi4orr48sLhAhXis4sKHUlXAJwQ_BIwFXoECAsQCw](url)
