### ISSUE TITLE
Список витрат

### ISSUE THREAD

**Issue by zoriana-melnyk** [zoriana-melnyk/Trip-to-the-Carpathians#12]

**Comment by irynaa-semchuk** [comment]
Давай я напишу список людей які їдуть в поїздку

**Comment by zoriana-melnyk** [comment]
Добре)

**Comment by irynaa-semchuk** [comment]
я додам ще список витрат на кожну особу

**Comment by irynaa-semchuk** [comment]
Я завантажила Excel-файл "Список_коштів"
Fixed#12

**Comment by irynaa-semchuk** [comment]
Fixed#12 Я завантажила Excel-файл "Список_коштів"
