### ISSUE TITLE
Траспорт

### ISSUE THREAD

**Issue by zoriana-melnyk** [zoriana-melnyk/Trip-to-the-Carpathians#2]
Пропоную їхати автобусом

**Comment by zoriana-melnyk** [comment]
https://infobus.eu/ua/bus/route/from-lviv-to-yaremche?admitad_uid=84e21302d7f132ef235217c82fad91ab

**Comment by irynaa-semchuk** [comment]
Давай краще електричкою))

**Comment by irynaa-semchuk** [comment]
[http://poezdato.net/raspisanie-poezdov/lvov--yaremche/](url)

**Comment by zoriana-melnyk** [comment]
Я проти. Автобусом комфортніше!
