### ISSUE TITLE
Проживання

### ISSUE THREAD

**Issue by irynaa-semchuk** [zoriana-melnyk/Trip-to-the-Carpathians#5]
Давай забронюємо номери у готелі.

**Comment by zoriana-melnyk** [comment]
Будинки:

1.  https://doba.ua/yaremche/1000711280.html
2. https://www.olx.ua/uk/obyavlenie/otdyh-v-karpatah-arenda-doma-vozle-bukovelya-vdpochinok-IDyz1PI.html#4e93ba3ace;promoted
3. https://www.olx.ua/uk/obyavlenie/karpati-yaremche-orenda-kotedzhv-blya-vodospadu-IDzk58C.html#4e93ba3ace;promoted

**Comment by irynaa-semchuk** [comment]
Мені подобається усі варіанти. Але потрібно щоб ціна підходила усім у групі.

**Comment by irynaa-semchuk** [comment]
Обговоривши це питання в групі, ми вибрали третій варіант)

**Comment by zoriana-melnyk** [comment]
Добре! Щодо кухні, там можна замовляти сніданок, обід та вечерю або ж готувати самостійно. Що обираємо?

**Comment by irynaa-semchuk** [comment]
Думаю, краще замовити сніданок і обід, а на вечір приготувати шашлики(в перший день).

**Comment by zoriana-melnyk** [comment]
Гаразд, переходимо до харчування #6
