### ISSUE TITLE
Витрати

### ISSUE THREAD

**Issue by zoriana-melnyk** [zoriana-melnyk/Trip-to-the-Carpathians#8]
Потрібно визначити загальну вартість поїздки

**Comment by zoriana-melnyk** [comment]
Добре, а за транспорт ми повинні заплатити 250 грн в обидві сторони

**Comment by zoriana-melnyk** [comment]
Харчування:

- Перший день:
 
1. сніданок - 30 грн
2. обід - 30 грн
3. вечеря - 100 грн

- Другий день:

1.  200 грн

- Третій день:

1. сніданок - 30 грн
2. обід - 30 грн

**Comment by irynaa-semchuk** [comment]
За культурну програму:

- Прогулянка містом 
 200 грн

- Екскурсія до водоспаду Пробій або ж Манявського водоспаду
250 грн

- Похід в гори:
50 грн

- Дегустація  місцевої кухні:
300 грн

**Comment by zoriana-melnyk** [comment]
Також варто розрахувати на додаткові витрати. Приблизно 200 грн
